{
 "title": "Cluster Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  avg(queries_running) AS \"Running\",\n  avg(queries_queued) AS \"Queued\",\n  avg(queries_blocked) AS \"Blocked\"\nFROM database_history\nWHERE\n  $__timeFilter(ctime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  avg(cpu_user) AS \"User\",\n  avg(cpu_sys) AS \"System\",\n  avg(cpu_user+cpu_sys) AS \"Total\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname != 'mdw'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  avg(ROUND(100.00 * mem_actual_used/mem_total, 2)) AS \"In use\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname != 'mdw'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  avg(disk_rb_rate) AS \"Read Rate\",\n  avg(-1.00 * disk_wb_rate) AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname != 'mdw'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  avg(net_rb_rate) AS \"Read Rate\",\n  avg(-1.00 * net_wb_rate) AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname != 'mdw'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  avg(load0) AS \"1 minute\",\n  avg(load1) AS \"5 minute\",\n  avg(load2) AS \"15 minute\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname != 'mdw'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  avg(swap_page_in) AS \"In use\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname != 'mdw'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}