{
 "title": "Storage Status",
 "description": "Disk capacity information and history",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Used Storage by Host Type",
   "type": "bargauge",
   "targets": [
    {
     "rawSql": "SELECT\n  hist.ctime AS \"time\",\n  CASE hosttype WHEN 'master' THEN 'Masters' WHEN 'sdw' THEN 'Segments' END AS metric,\n  100* SUM(bytes_used)/SUM(total_bytes) AS \"Disk Space Used\"\nFROM gpmetrics.gpcc_disk_history_view hist, (SELECT MAX(ctime) AS ctime FROM gpmetrics.gpcc_disk_history_view) last_\nWHERE\n  hist.ctime = last_.ctime\nGROUP BY hist.ctime, metric\nORDER BY metric"
    }
   ]
  },
  {
   "title": "GP Masters, Storage Usage History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  SUM(bytes_used) AS \"Disk Space Used\"\nFROM gpmetrics.gpcc_disk_history_view\nWHERE\n  $__timeFilter(ctime) AND\n  hosttype = 'master'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "GP Masters, Storage Usage History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  SUM(bytes_available) AS \"Disk Space Available\"\nFROM gpmetrics.gpcc_disk_history_view\nWHERE\n  $__timeFilter(ctime) AND\n  hosttype = 'master'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Free Storage % by Host Type",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist.ctime AS \"time\",\n  CASE hosttype WHEN 'master' THEN 'Masters' WHEN 'sdw' THEN 'Segments' END AS metric,\n  100* SUM(bytes_available)/SUM(total_bytes) AS \"Disk Space Available\"\nFROM gpmetrics.gpcc_disk_history_view hist, (SELECT MAX(ctime) AS ctime FROM gpmetrics.gpcc_disk_history_view) last_\nWHERE\n  hist.ctime = last_.ctime\nGROUP BY hist.ctime, metric\nORDER BY metric"
    }
   ]
  },
  {
   "title": "GP Segments, Storage Usage History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  SUM(bytes_used) AS \"Disk Space Used\"\nFROM gpmetrics.gpcc_disk_history_view\nWHERE\n  $__timeFilter(ctime) AND\n  hosttype = 'sdw'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "GP Segments, Storage Usage History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  SUM(bytes_available) AS \"Disk Space Available\"\nFROM gpmetrics.gpcc_disk_history_view\nWHERE\n  $__timeFilter(ctime) AND\n  hosttype = 'sdw'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Free Storage by Host Type",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist.ctime AS \"time\",\n  CASE hosttype WHEN 'master' THEN 'Masters' WHEN 'sdw' THEN 'Segments' END AS metric,\n  SUM(total_bytes) AS \"Disk Space Total\"\nFROM gpcc_disk_history_view hist, (SELECT MAX(ctime) AS ctime FROM gpmetrics.gpcc_disk_history_view) last_\nWHERE\n  hist.ctime = last_.ctime\nGROUP BY hist.ctime, metric\nORDER BY metric"
    }
   ]
  },
  {
   "title": "GP Segments,  Used Storage % by Hostname, Data Directory",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist.ctime AS \"time\",\n  (hostname, filesystem) AS \"metric\",\n  100.00 * bytes_used / total_bytes AS \"bytes_used_perc\"\nFROM gpmetrics.gpcc_disk_history_view hist, (SELECT MAX(ctime) AS ctime FROM gpmetrics.gpcc_disk_history_view) last_\nWHERE\n  hosttype = 'sdw'\n  AND hist.ctime = last_.ctime\nGROUP BY hist.ctime, hostname, filesystem, bytes_used, total_bytes\nORDER BY hostname, filesystem"
    }
   ]
  },
  {
   "title": "GP Segments, Free Storage % by Hostname, Data Directory",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist.ctime AS \"time\",\n  (hostname, filesystem) AS \"metric\",\n  100.00 * bytes_available / total_bytes AS bytes_available_perc\nFROM gpmetrics.gpcc_disk_history_view hist, (SELECT MAX(ctime) AS ctime FROM gpmetrics.gpcc_disk_history_view) last_\nWHERE\n  hosttype = 'sdw'\n  AND hist.ctime = last_.ctime\nGROUP BY hist.ctime, hostname, filesystem, bytes_available, total_bytes\nORDER BY hostname, filesystem"
    }
   ]
  },
  {
   "title": "GP Segments, Free Storage by Hostname, Data Directory",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist.ctime AS \"time\",\n  (hostname, filesystem) AS \"metric\",\n  bytes_available\nFROM gpmetrics.gpcc_disk_history_view hist, (SELECT MAX(ctime) AS ctime FROM gpmetrics.gpcc_disk_history_view) last_\nWHERE\n  hosttype = 'sdw'\n  AND hist.ctime = last_.ctime\nGROUP BY hist.ctime, hostname, filesystem, bytes_available\nORDER BY hostname, filesystem"
    }
   ]
  },
  {
   "title": "GP Segments, Storage Total by Hostname, Data Directory",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  hist.ctime AS \"time\",\n  (hostname, filesystem) AS \"metric\",\n  total_bytes AS \"total_bytes\"\nFROM gpmetrics.gpcc_disk_history_view hist, (SELECT MAX(ctime) AS ctime FROM gpmetrics.gpcc_disk_history_view) last_\nWHERE\n  hosttype = 'sdw'\n  AND hist.ctime = last_.ctime\nGROUP BY hist.ctime, hostname, filesystem, total_bytes\nORDER BY hostname, filesystem"
    }
   ]
  }
 ]
}