{
 "title": "Host Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": " SELECT hostname from pg_catalog.gp_segment_configuration GROUP BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "System CPU (%)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  cpu_sys AS \"System (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname IN ($host)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "User CPU (%)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  cpu_user AS \"User (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Idle CPU (%)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  cpu_idle AS \"Idle (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname IN ($host)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(mem_actual_used, 2) AS \"Used\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname IN ($host)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Used Memory (%)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(100.00 * mem_actual_used/mem_total, 2) AS \"Used (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname IN ($host)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Available Memory (%)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(100.00 * mem_actual_free/mem_total, 2) AS \"Available (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  mem_total AS \"Used\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname IN ($host)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disk IO (Read)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(disk_rb_rate::DECIMAL, 2) AS \"Read Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname IN ($host)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disk Skew",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(disk_wb_rate::DECIMAL, 2) AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Network I/O (Read)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(net_rb_rate::DECIMAL, 2) AS \"Read Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname IN ($host)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Network I/O (Write)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(net_wb_rate::DECIMAL, 2) AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  }
 ]
}