{
 "title": "Query Details",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "search_queryid", "label": "QueryID", "query": "*" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  query_id AS \"Query\",\n  query_user AS \"User\",\n  query_database AS \"Database\",\n  query_res_group AS \"Resource Group\",\n  query_planner AS \"Planner\"\nFROM queries_history_dashboard_view\nWHERE\n  query_id = '$search_queryid'\nORDER BY 1"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  cpu_master_percent,\n  cpu_segs_percent,\n  cpu_segs,\n  skew_cpu\nFROM gpmetrics.gpcc_queries_history\nWHERE\n  tmid || '-' || ssid || '-' || ccnt = '$search_queryid'\nORDER BY 1"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  query_ended_time AS \"time\",\n  query_submitted_time AS \"Submitted\",\n  query_queued_time AS \"Queued Time\",\n  query_run_time AS \"Run Time\",\n  query_ended_time AS \"Ended\"\nFROM queries_history_dashboard_view\nWHERE\n  query_id = '$search_queryid'\nORDER BY 1"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  memory,\n  spill_size,\n  disk_read_bytes,\n  disk_write_bytes\nFROM gpmetrics.gpcc_queries_history\nWHERE\n  tmid || '-' || ssid || '-' || ccnt = '$search_queryid'\nORDER BY 1"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  query_text AS \"Query Text\"\nFROM queries_history_dashboard_view\nWHERE\n  query_id = '$search_queryid'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Row Skew",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  'Step ' || nodeid || ' : ' || node_type AS metric,\n  avg(row_skew) AS \"row_skew\"\nFROM queries_history_details_dashboard_view\nWHERE\n  $__timeFilter(ctime) AND\n  tmid || '-' || ssid || '-' || ccnt = '$search_queryid'\nGROUP BY 1, nodeid, node_type\nORDER BY 1, nodeid"
    }
   ]
  },
  {
   "title": "Actual vs. Estimated Rows",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  'Step ' || nodeid || ' : ' || node_type AS metric,\n  avg(planrows_sum) AS \"Estimated Rows\",\n  avg(total_cost_sum) AS \"Actual Rows\"\nFROM queries_history_details_dashboard_view\nWHERE\n  $__timeFilter(ctime) AND\n  tmid || '-' || ssid || '-' || ccnt = '$search_queryid'\nGROUP BY 1, 2\nORDER BY 1, 2 DESC"
    }
   ]
  },
  {
   "title": "Estimation Accuracy",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  'Step ' || nodeid || ' : ' || node_type AS metric,\n  avg(estimation_accuracy) AS \"estimation_accuracy\"\nFROM queries_history_details_dashboard_view\nWHERE\n  $__timeFilter(ctime) AND\n  tmid || '-' || ssid || '-' || ccnt = '$search_queryid'\nGROUP BY 1, 2\nORDER BY 1, 2 DESC"
    }
   ]
  }
 ]
}