{
 "title": "Greenplum Command Center",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Queries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  queries_running\nFROM database_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  queries_total\nFROM database_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  bytes_available_perc\nFROM vw_disk_space_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Read Ops per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  disk_ro_rate\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Read Bytes per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  disk_rb_rate\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  cpu_idle\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU Usage (System)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  cpu_sys\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU Load1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  load1::decimal\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  queries_blocked\nFROM database_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Queued Queries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  queries_queued\nFROM database_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Free Memory (Actual)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  ROUND(100*SUM(mem_actual_free::DECIMAL)/SUM(mem_total::DECIMAL), 2) AS \"mem_actual_free_perc\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Write Ops per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  disk_wo_rate\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Write Bytes per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  disk_wb_rate\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU Usage (User)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  cpu_user\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU Load0",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  load0::decimal\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU Load2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  load2::decimal\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  { "title": "Disk Space Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "content": "### Available Disk Space\n\n\n\n"
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  bytes_available_perc\nFROM vw_disk_space_history_perhost\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  bytes_available\nFROM vw_disk_space_history_perhost\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  bytes_available\nFROM vw_disk_space_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  bytes_available_perc\nFROM vw_disk_space_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 }, "content": "## Disk Space Used\n\n\n\n" },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  bytes_used_perc\nFROM vw_disk_space_history_perhost\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  bytes_used\nFROM vw_disk_space_history_perhost\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  bytes_used\nFROM vw_disk_space_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  bytes_used_perc\nFROM vw_disk_space_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  hostname AS metric,\n  sum(mem_actual_used) AS \"mem_total\"\nFROM system_history\nWHERE\n  $__timeFilter(ctime)\nGROUP BY 1, hostname,2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 25 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  sum(mem_total) / sum(mem_actual_used) AS \"mem_total\"\nFROM system_history\nWHERE\n  $__timeFilter(ctime)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 28 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(ctime,$__interval),\n  sum(mem_actual_used) AS \"mem_total\"\nFROM system_history\nWHERE\n  $__timeFilter(ctime)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}