{
 "title": "Cluster Info",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPUs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Threads",
   "type": "table",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Available RAM %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used RAM %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO (Read)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host.Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT difference(mean(\"write_bytes\")), difference(mean(\"read_bytes\")) FROM \"diskio\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host.Usage_User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "$tag_host.Usage_System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "$tag_host.Usage_Iowait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_iowait\") FROM \"cpu\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path on $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "<>", "value": "/" },
      { "condition": "AND", "key": "path", "operator": "<>", "value": "/boot" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO (Write)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host.Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT difference(mean(\"write_bytes\")), difference(mean(\"read_bytes\")) FROM \"diskio\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  }
 ]
}