{
 "title": "Pivotal Greenplum Command Center Host Metrics 4",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": " SELECT hostname from pg_catalog.gp_segment_configuration GROUP BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  cpu_sys AS \"System (%)\",\n  cpu_user AS \"User (%)\",\n  cpu_idle AS \"Idle (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disk Skew",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  -1.00 * disk_rb_rate AS \"Read Rate\",\n  disk_wb_rate AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(100.00 * mem_actual_used::DECIMAL/mem_total::DECIMAL, 2) AS \"Used (%)\",\n  ROUND(100.00 * mem_actual_free::DECIMAL/mem_total::DECIMAL, 2) AS \"Free (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Network Skew",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  -1.00 * net_rb_rate AS \"Read Rate\",\n  net_wb_rate AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  }
 ]
}