{
 "title": "Pivotal Greenplum Command Center Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "severity_level_var", "label": "Severity Level", "query": "PANIC,FATAL,ERROR,WARNING" }
  ]
 },
 "panels": [
  {
   "title": "Database State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS status, now() AS ctime\nFROM gpstate\nWHERE \"output\" LIKE '%All segments are running normally';"
    }
   ]
  },
  {
   "title": "Segment Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT CASE status WHEN 'u' THEN 'Up' ELSE 'Down' END AS status, MAX(count) AS status_cnt\nFROM (\n    SELECT status, COUNT(*)\n    FROM pg_catalog.gp_segment_configuration\n    WHERE content <> -1\n    GROUP BY status\n    UNION \n    SELECT 'd', 0\n    UNION \n    SELECT 'u', 0) foo\nGROUP BY status\nORDER BY status DESC;"
    }
   ]
  },
  {
   "title": "Uptime (master)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mdw" }
     ]
    }
   ]
  },
  {
   "title": "GPDB Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT Version[1] FROM (SELECT regexp_matches(VERSION(), '.*Greenplum Database(.*) build commit.*') AS Version) A;"
    }
   ]
  },
  {
   "title": "GPCC Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "rawSql": "SELECT * FROM gpcc_version;" }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT COUNT(sess_id)-1 FROM pg_catalog.pg_stat_activity"
    }
   ]
  },
  {
   "title": "Free Disk Space (Master Instances)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n  FLOOR((EXTRACT(epoch FROM now())/60)*60) AS \"time\", \n  ROUND(100 * SUM(bytes_available::DECIMAL/1024/1024/1024) / SUM(total_bytes::DECIMAL/1024/1024/1024), 2) AS \"Free Disk Space (%)\"\nFROM gpcc_disk_now_view dnv\nWHERE\n  hosttype = 'master'\nGROUP BY \n  1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  FLOOR((EXTRACT(epoch FROM now())/60)*60) AS \"time\",\n  ROUND(SUM(bytes_available::DECIMAL), 2) AS \"Disk Space Free\"\nFROM gpcc_disk_now_view dnv\nWHERE\n  hosttype = 'master'\nGROUP BY \n  1"
    }
   ]
  },
  {
   "title": "Disk Space in Use (Master Instances)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n  FLOOR((EXTRACT(epoch FROM now())/60)*60) AS \"time\",\n  ROUND(100 * SUM(bytes_used::DECIMAL/1024/1024/1024) / SUM(total_bytes::DECIMAL/1024/1024/1024), 2) AS \"Disk Space in Use (%)\"\nFROM gpcc_disk_now_view dnv\nWHERE\n  hosttype = 'master'\nGROUP BY \n  1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  FLOOR((EXTRACT(epoch FROM now())/60)*60) AS \"time\",\n  ROUND(SUM(bytes_used::DECIMAL), 2) AS \"Disk Space in Use\"\nFROM gpcc_disk_now_view dnv\nWHERE\n  hosttype = 'master'\nGROUP BY \n  1"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  queries_running,\n  queries_queued,\n  queries_blocked\nFROM database_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Free Disk Space (Segment Instances)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n  FLOOR((EXTRACT(epoch FROM now())/60)*60) AS \"time\", \n  ROUND(100 * SUM(bytes_available::DECIMAL/1024/1024/1024) / SUM(total_bytes::DECIMAL/1024/1024/1024), 2) AS \"Free Disk Space (%)\"\nFROM gpcc_disk_now_view dnv\nWHERE\n  hosttype = 'sdw'\nGROUP BY \n  1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  FLOOR((EXTRACT(epoch FROM now())/60)*60) AS \"time\",\n  ROUND(SUM(bytes_available::DECIMAL), 2) AS \"Disk Space Free\"\nFROM gpcc_disk_now_view dnv\nWHERE\n  hosttype = 'sdw'\nGROUP BY \n  1"
    }
   ]
  },
  {
   "title": "Disk Space in Use (Segment Instances)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n  FLOOR((EXTRACT(epoch FROM now())/60)*60) AS \"time\",\n  ROUND(100 * SUM(bytes_used::DECIMAL/1024/1024/1024) / SUM(total_bytes::DECIMAL/1024/1024/1024), 2) AS \"Disk Space in Use (%)\"\nFROM gpcc_disk_now_view dnv\nWHERE\n  hosttype = 'sdw'\nGROUP BY \n  1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  FLOOR((EXTRACT(epoch FROM now())/60)*60) AS \"time\",\n  ROUND(SUM(bytes_used::DECIMAL), 2) AS \"Disk Space in Use\"\nFROM gpcc_disk_now_view dnv\nWHERE\n  hosttype = 'sdw'\nGROUP BY \n  1"
    }
   ]
  },
  {
   "title": "Alerts from pg_log",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  logtime AS \"time\",\n  logseverity,\n  logmessage,\n  loguser,\n  logdatabase,\n  loghost\nFROM gp_toolkit.gp_log_system\nWHERE\n  $__timeFilter(logtime) AND\n  logseverity IN ($severity_level_var)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  cpu_sys,\n  cpu_user,\n  cpu_sys + cpu_user AS \"cpu_total\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  ROUND(100 * mem_actual_used::DECIMAL / (mem_actual_used + mem_actual_free), 2) AS \"mem_actual_used_perc\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  }
 ]
}