{
 "title": "Pivotal Greenplum Command Center Host Metrics 1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": " SELECT hostname from pg_catalog.gp_segment_configuration GROUP BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage ($host)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  cpu_sys AS \"System (%)\",\n  cpu_user AS \"User (%)\",\n  cpu_idle AS \"Idle (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname = $host\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory Usage ($host)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  ROUND(100.00 * mem_actual_used::DECIMAL/mem_total::DECIMAL, 2) AS \"Used (%)\",\n  ROUND(100.00 * mem_actual_free::DECIMAL/mem_total::DECIMAL, 2) AS \"Available (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname = $host\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory Metrics ($host)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  ROUND(mem_actual_used::DECIMAL, 2) AS \"Used\",\n  ROUND(mem_actual_free::DECIMAL, 2) AS \"Available\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname = $host\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Skew ($host)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  ROUND(disk_rb_rate::DECIMAL, 2) AS \"Read Rate\",\n  ROUND(disk_wb_rate::DECIMAL, 2) AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname = $host\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Network Skew ($host)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  ROUND(net_rb_rate::DECIMAL, 2) AS \"Read Rate\",\n  ROUND(net_wb_rate::DECIMAL, 2) AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime) AND\n  hostname = $host\nORDER BY 1"
    }
   ]
  }
 ]
}