{
 "title": "Pivotal Greenplum Command Center Host Metrics 3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": " SELECT hostname from pg_catalog.gp_segment_configuration GROUP BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "System CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  cpu_sys AS \"System (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "User CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  cpu_user AS \"User (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Idle CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  cpu_idle AS \"Idle (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Used Memory Metrics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes", "label": "Used Memory" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(mem_actual_used, 2) AS \"Used\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Used Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "Used Memory" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(100.00 * mem_actual_used/mem_total, 2) AS \"Used\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Available Memory Metrics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes", "label": "Used Memory" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(mem_actual_free, 2) AS \"Free\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Available Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent", "label": "Used Memory" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(100.00 * mem_actual_free/mem_total, 2) AS \"Free\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disk skew",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  -1.00 * disk_wb_rate AS \"Write\",\n  disk_rb_rate AS \"Read\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Network skew",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  -1.00 * net_wb_rate AS \"Write\",\n  net_rb_rate AS \"Read\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  }
 ]
}