{
 "title": "Pivotal Greenplum Command Center Host Metrics 2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": " SELECT hostname from pg_catalog.gp_segment_configuration GROUP BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  cpu_sys AS \"System (%)\",\n  cpu_user AS \"User (%)\",\n  cpu_idle AS \"Idle (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Memory Metrics",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(mem_actual_used, 2) AS \"Used\",\n  ROUND(mem_actual_free, 2) AS \"Available\",\n  ROUND(mem_total, 2) AS \"Total\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(100.00 * mem_actual_used/mem_total, 2) AS \"Used (%)\",\n  ROUND(100.00 * mem_actual_free/mem_total, 2) AS \"Available (%)\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disk Skew",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(disk_rb_rate::DECIMAL, 2) AS \"Read Rate\",\n  ROUND(disk_wb_rate::DECIMAL, 2) AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Network Skew",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  hostname AS metric,\n  ROUND(net_rb_rate::DECIMAL, 2) AS \"Read Rate\",\n  ROUND(net_wb_rate::DECIMAL, 2) AS \"Write Rate\"\nFROM gpcc_system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1,2"
    }
   ]
  }
 ]
}