{
 "title": "Dash2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ENV", "query": "postgres" },
   {
    "name": "sess_id",
    "query": "SELECT ssid FROM queries_history WHERE $__timeFilter(ctime) ORDER BY ssid"
   }
  ]
 },
 "panels": [
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage by user session (normalized to whole cluster max cpu capacity)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT ctime AS time,\n       'con'||sessid AS metric1,\n       cpu/6/48  -- divide by cores and hosts count\n       --vmemsz/1024/1024 vmemGB\nFROM sess_cpu_history\nWHERE\n  $__timeFilter(ctime)\n--GROUP BY 1,2 \nORDER by 1,2 desc;"
    }
   ]
  },
  {
   "title": "read MBps by user sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH \r\nquh AS (SELECT ssid,\r\n               regexp_replace(substr(query_text,0,200),E'[\\\\n\\\\r ]+', ' ', 'g' ) AS query\r\n        FROM queries_history \r\n        WHERE ($__timeFrom()::timestamp with time zone, $__timeTo()::timestamp) OVERLAPS (tstart,tfinish)\r\n        UNION ALL\r\n        SELECT sess_id,\r\n               regexp_replace(substr(current_query,0,200),E'[\\\\n\\\\r ]+', ' ', 'g' )\r\n        FROM pg_stat_activity\r\n        GROUP BY 1,2),\r\nioh AS (SELECT ctime::timestamp with time zone AS ct,\r\n               sess_id,username||'@'||db AS user,\r\n               state,\r\n               \"rKBps\"/1024 AS rMBps\r\n        FROM sess_io_history\r\n        WHERE ctime AT TIME ZONE 'UTC' BETWEEN $__timeFrom() AND $__timeTo()\r\n        )\r\nSELECT date_trunc('minute', ioh.ct) AS time,\r\n  AVG(rMBps), -- Mind: this includes only user sessions. Add segment server process stats (pidstat -dl 1 15| grep -E \"Average.*postgres.*(silent|process)\") to complement to queries_history.net_rb_rate\r\n  coalesce(ioh.user||' \\\\ con'||quh.ssid||': '||quh.query,'Others<20sec') AS metric\r\nFROM ioh LEFT JOIN quh ON quh.ssid=ioh.sess_id\r\nAND rMBps>1\r\nGROUP BY 1,3\r\nORDER BY 1,3;"
    }
   ]
  },
  {
   "title": "Memory usage by user sessions (RSS on all nodes) in GB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT ctime AS time,\n       'con'||sessid AS metric,\n       --cpu/6/48  -- divide by cores and hosts count\n       rss/1024/1024 vmemGB -- RSS can also include shared memory so don't be surprised if total physical memory is oversubscribed\nFROM sess_cpu_history\nWHERE\n  $__timeFilter(ctime)\n--GROUP BY 1,2 \nORDER by 1,2 desc;"
    }
   ]
  },
  {
   "title": "Queries History",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT ssid,\n       regexp_replace(substr(query_text,0,200),E'[\\\\n\\\\r ]+', ' ', 'g' ) AS query\nFROM queries_history\nWHERE ssid IN(${sess_id:csv}) and\n  $__timeFilter(ctime)\nORDER BY ssid"
    }
   ]
  },
  { "title": "Panel Title", "type": "natel-discrete-panel", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 } },
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "SEGMENTS UP",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "select (100*avg(case when status='u' then 1 else 0 end))::smallint as state from gp_segment_configuration;"
      }
     ]
    },
    {
     "title": "Segments",
     "type": "table",
     "gridPos": { "h": 3, "w": 3, "x": 2, "y": 2 },
     "targets": [
      {
       "rawSql": "select case when mode='s' then 'SYNCED' when mode='r' then 'DOWN' when mode='c' then 'CHANGE TRACKING' end,count(*)::integer from gp_segment_configuration group by 1 order by 1;"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 5, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "select count(*) from pg_stat_activity;\n"
      }
     ]
    },
    {
     "title": "Queries Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "rawSql": "SELECT\n  $__time(ctime::timestamp with time zone),\n  queries_total\nFROM\n  database_history\nWHERE\n  $__timeFilter(ctime::timestamp with time zone)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 15, "w": 14, "x": 10, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT \n  CASE WHEN (logseverity='PANIC' OR logmessage LIKE '%checksum does not match%' OR logmessage LIKE '%access status of transaction%' OR logmessage LIKE '%Could not open file%pg_clog%' OR logmessage LIKE '%Error on receive from seg%' OR logmessage LIKE '%invalid memory alloc request%') THEN 1 \n       WHEN ((logseverity='FATAL' AND logmessage NOT LIKE 'no pg_hba.conf entry for host %' AND logmessage NOT LIKE 'database % does not exist') OR logmessage LIKE '%deadlock%' OR logmessage LIKE '%Out of memory%') THEN 2 \n       WHEN logmessage LIKE 'no pg_hba.conf entry for host %' OR logmessage LIKE 'database % does not exist' THEN 5\n       WHEN logseverity='ERROR' THEN 3 ELSE 4 END AS sev,\n  to_char(logtime,'YYYY/MM/DD HH24:MI:SS') AS time,\n  logdatabase,\n  regexp_replace(regexp_replace(logmessage,E'( .cdbdisp.*|http response code | .url_curl.c:455. )', '', 'g'),E'effective url: .* error code', 'error code', '')\nFROM\n  ext_log_today\nWHERE\n  logdatabase!='gpperfmon' AND\n  logseverity in ('PANIC','FATAL','ERROR') AND\n  logmessage not like 'too many connections for role%' AND\n  logmessage not like 'column \"pid\" does not exist%' AND\n  logmessage not like 'division by zero' AND\n  logmessage not like '%metastage_loc_info%'\n  /*$__timeFilter(logtime)*/\nORDER BY logtime DESC"
      }
     ]
    },
    {
     "title": "GP Engine Events",
     "type": "table",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT \n  to_char(time,'YYYY/MM/DD HH24:MI:SS') AS time,\n  replace(hostname,'.msk.trd.ru',''),\n  fselocation,\n  c.dbid::int,\n  h.desc\nFROM\n  gp_segment_configuration c,\n  gp_configuration_history h,\n  pg_filespace_entry f \nWHERE\n  h.dbid=c.dbid and \n  c.dbid=f.fsedbid and\n  now()-time<interval '4 week'\n  --and $__timeFilter(time)\nORDER BY 1 DESC"
      }
     ]
    },
    {
     "title": "OS Events (latest /var/log/messages)",
     "type": "table",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT \n  ctime,\n  hostname,\n  msg\nFROM\n  varlogmessages_history\nWHERE\n  now()-ctime<interval '4 week' and \n  $__timeFilter(ctime)\nORDER BY 1 DESC"
      }
     ]
    },
    {
     "title": "LOCKED QUERIES",
     "type": "table",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "select \n      extract(minute from now()-query_start) as MINUTES,\n      datname,\n      procpid,\n      usename,\n      client_addr,\n      regexp_replace(substr(current_query,0,200),E'[\\\\n\\\\r ]+', ' ', 'g' ) \nfrom pg_stat_activity \nwhere waiting \norder by 1 desc;"
      }
     ]
    },
    {
     "title": "LOCKS longer than 10 MIN",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "--select procpid,datname,usename,client_addr,waiting_reason,count(*) as CNT from pg_stat_activity where waiting and current_query <> '<IDLE>' group by 1,2,3,4,5;\n\nselect distinct db,\n      substr(wait_q_started::text,0,20) AS wait_q_started,\n      user_waits,\n      query_waits,\n      substr(block_q_started::text,0,20) AS block_q_started,\n      user_blocker,\n      query_blocker,\n      extract(minute from wait_q_started-block_q_started) AS lock_duration\nfrom locks_log_ext \nwhere wait_q_started-block_q_started>interval '10 minute' and \n      query_blocker!='<IDLE>' and\n      $__timeFilter(wait_q_started::timestamp with time zone)"
      }
     ]
    }
   ]
  },
  {
   "title": "General Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU_SYS anomalies",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH top1cpu_sys AS (\nselect * from \n\t(select ctime::timestamp with time zone,hostname,cpu_sys,row_number() over (partition by ctime order by cpu_sys desc) as rn \n\tfrom system_history \n\twhere hostname not like '%master%' and $__timeFilter(ctime::timestamp with time zone)) subqq \n\twhere subqq.rn=1), top2cpu_sys AS (\nselect * from \n\t(select ctime::timestamp with time zone,hostname,cpu_sys,row_number() over (partition by ctime order by cpu_sys desc) as rn \n\tfrom system_history \n\twhere hostname not like '%master%' and $__timeFilter(ctime::timestamp with time zone)) subqq \n\twhere subqq.rn=2)\nSELECT t1.ctime::timestamp with time zone AS time,t1.hostname,t1.cpu_sys as highest_cpu_sys--,t2.cpu_sys as other_cpu_sys \nFROM top1cpu_sys t1,top2cpu_sys t2 \nWHERE t1.ctime=t2.ctime and t1.cpu_sys-t2.cpu_sys>20\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "SWAP activity",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  max(swap_page_in) pages_IN,\n  max(swap_page_out) pages_OUT \nFROM system_history\nWHERE\n  $__timeFilter(ctime::timestamp with time zone)\ngroup by ctime\nORDER BY 1"
      }
     ]
    },
    {
     "title": "max_CPU_util %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  max(cpu_user+cpu_sys) AS \"max cpu util\"\n  --hostname,\n  --avg(cpu_user+cpu_sys) OVER (ORDER BY ctime ROWS 4 PRECEDING) AS \"cpu util\"\nFROM system_history\nWHERE\n  $__timeFilter(ctime::timestamp with time zone)\ngroup by ctime--,cpu_user,cpu_sys,hostname\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Total Cluster GBps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(ctime::timestamp with time zone,1m,0),\n  hostname AS metric,\n  avg(disk_rb_rate+disk_wb_rate)/1024/1048/1024 AS \"GBps\"  -- disk_*b_rate measured in sectors (512 byte)\nFROM system_history\nWHERE\n  hostname not like 'gp-master%' AND\n  $__timeFilter(ctime::timestamp with time zone)\nGROUP BY 1,2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Spill Files by DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  now AS \"time\",\n  datname,\n  sum(size)/1024/1024/1024 AS sum_spills_GB\nFROM spill_all\nWHERE\n  $__timeFilter(now)\ngroup by 1,2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Responce Time AGG over 1min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(ctime::timestamp with time zone,1m,0),\n  hostname AS metric,\n  avg(await) AS \"await\"\nFROM sar_disk\nWHERE\n  $__timeFilter(ctime::timestamp with time zone)\nGROUP BY 1,2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Spill Files by Username",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  now AS \"time\",\n  usename,\n  sum(size)/1024/1024/1024 AS sum_spills_GB\nFROM spill_all\nWHERE\n  $__timeFilter(now)\ngroup by 1,2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Total Cluster IOPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(ctime::timestamp with time zone,1m,0),\n  hostname AS metric,\n  avg(disk_ro_rate+disk_wo_rate) AS \"Iops\"\nFROM system_history\nWHERE\n  hostname not like 'gp-master%' AND\n  $__timeFilter(ctime::timestamp with time zone)\nGROUP BY 1,2\nORDER BY 1,2\n"
      }
     ]
    },
    {
     "title": "Spill Files by Segment #",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  now AS \"time\",\n  'seg'||segid,\n  sum(size)/1024/1024/1024 AS sum_spills_GB\nFROM spill_all\nWHERE\n  $__timeFilter(now)\ngroup by now,segid\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "SEGMENT_SPACE % used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  hostname,\n  max(100*bytes_used/total_bytes::bigint) AS max_seg_space_used\nFROM diskspace_history\nWHERE\n  filesystem like '/data%' and\n  filesystem not like '%db_dumps' and\n  $__timeFilter(ctime::timestamp with time zone)\ngroup by 1,2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "QUERIES",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime AS \"time\",\n  queries_total,\n  queries_running,\n  queries_queued\nFROM database_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "DUMP_SPACE % used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  hostname,\n  max(100*bytes_used/total_bytes::bigint) AS max_seg_space_used\nFROM diskspace_history\nWHERE\n  filesystem like '%db_dumps' and\n  $__timeFilter(ctime::timestamp with time zone)\ngroup by 1,2\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "Per Host Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU_user %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  hostname,\n  cpu_user\nFROM system_history\nWHERE\n  $__timeFilter(ctime::timestamp with time zone)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "CPU_sys %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  hostname,\n  cpu_sys\nFROM system_history\nWHERE\n  $__timeFilter(ctime::timestamp with time zone  )\nORDER BY 1"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  hostname,\n  disk_ro_rate+disk_wo_rate AS Iops\nFROM system_history\nWHERE\n  $__timeFilter(ctime::timestamp with time zone)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "MBps",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  hostname,\n  (disk_rb_rate+disk_wb_rate)/1024/1024 AS MBps\nFROM system_history\nWHERE\n  $__timeFilter(ctime::timestamp with time zone)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "MEMORY %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  hostname,\n  100*mem_used/mem_total AS mem_pct\nFROM system_history\nWHERE\n  $__timeFilter(ctime::timestamp with time zone)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "NETWORK rx/tx (max Bps)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  ctime::timestamp with time zone AS \"time\",\n  max(net_rb_rate) AS RX,-1*max(net_wb_rate) AS TX\nFROM system_history\nWHERE\n  $__timeFilter(ctime::timestamp with time zone)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "pg_stat_activity",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT \n  'con'||ssid,\n  regexp_replace(substr(query_text,0,200),E'[\\\\n\\\\r ]+', ' ', 'g' )\nFROM\n  queries_history\nWHERE\n  $__timeFilter(ctime)\n  --AND ssid=$var-ssid\nORDER BY 1 DESC"
      }
     ]
    },
    {
     "title": "test bar graph",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  extract(minute from (et-st)) as value,\n  msg AS metric,\n  maint_ctime as time\nFROM tmp_maint\nORDER BY st"
      }
     ]
    }
   ]
  }
 ]
}